In [1]:
import pandas as pd

In [13]:
df = pd.read_csv("../data/pokemon_data.csv")
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# Changes to the data

if you are going to change the data make sure you use an assignement operator to dataframe to make sure the changes are saved. Otherwise, the changes will be temporary and will not be reflected in the original data frame.

well not in all cases like when you are using inplace = True, but in general, it is a good practice to use an assignment operator to make sure the changes are saved.


also this one doesnt need an assignment variable = df.loc[0:5, 'Name'] = "Ivysaur"

===================================================================
## “Functions usually DO NOT change df unless told”

If you see a function like:

df.drop()

df.sort_values()

df.fillna()

df.rename()

It returns a NEW DataFrame

## but if you want it to modify the dataframe directly then you need to use inplace = True

### Option A: reassign

df = df.drop(columns=['Total'])

### Option B: inplace (rarely recommended)

df.drop(columns=['Total'], inplace=True)

=================================================================
## “Assignment ALWAYS changes the DataFrame”

If you see = with .loc / .iloc:

df.loc[0:5, 'Name'] = "Ivysaur"

df.iloc[0, 1] = 10

df['col'] = something

This modifies df directly

## add a column

In [3]:
df['Total' ] = df['HP' ] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def' ] + df['Speed']

In [4]:
df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

## drop a column

In [5]:
df = df.drop(columns=['Total'])

In [6]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [7]:
df['Total'] = df.iloc[:,4:10].sum(axis=1) 
#[:] means all rows
#[4:9] means “Take columns 4 to 9 and sum them row by row, store in Total”

# iloc indexing starts  at 0 thats why we start at 4 instead of 5
# 0 → #
# 1 → Name
# 2 → Type 1
# 3 → Type 2
# 4 → HP
# 5 → Attack
# 6 → Defense
# 7 → Sp. Atk
# 8 → Sp. Def
# 9 → Speed
# 10 → Generation
# 11 → Legendary
# 12 → Total
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

# moving the columns around

in this case we are moving the total

In [8]:
cols = list(df.columns)

df = df[cols[0:4] + [cols[-1]] + cols[4:12]]

df.head(5)

##====== my mistake ==========
# df = df[cols[0:4] + cols[-1] + cols[4:12]]

# This part is wrong:

# cols[-1]

# Because:

# cols[-1] is a single string (e.g. "Total")
# you cannot add a string to a list

# So this will crash or behave incorrectly.

## cols[0:4] and cols[4:12] are not strings because they are a range therefore a list

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

# Saving or exporting our data to CSV

In [9]:
df.to_csv('cleaned/modified.csv')
df.to_csv('cleaned/no_index_modified.csv', index=False) #if youi dont want the index column on your data
df.to_csv('cleaned/modified.txt', index=False, sep='|') # initiating separator

## saved to the folder called cleaned

## lets read  it

In [10]:
new_df = pd.read_csv('cleaned/modified.csv')
new_df

,Unnamed: 0,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [11]:
no_index_new_df = pd.read_csv('cleaned/no_index_modified.csv')
no_index_new_df

## dont worry the index is not visible on the excel but on jupyter it just has to exist

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [12]:
df_txt = pd.read_csv('cleaned/modified.txt', delimiter='|')
df_txt

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [ ]:
### because wehn you export a new data frame the index deosnt get changed as well
reset_index_df = df
reset_index_df = reset_index_df.reset_index()
reset_index_df.to_csv('cleaned/reset_index_modified.csv')